### ISSUE TITLE
empty recursion

### ISSUE THREAD

**Issue by jonaprieto** [martinescardo/HoTT-UF-Agda-Lecture-Notes#11]
https://github.com/martinescardo/HoTT-UF-Agda-Lecture-Notes/blob/f39416340927aa9f960b00d65315e3c6feaf7490/HoTT-UF-Agda.lagda#L688

Follow the pattern of presenting recursion as the particular case of induction, for reading,
it might be better to say, another name for this is `𝟘-recursion`. Maybe first than these names `is-empty` and negation.

**Comment by martinescardo** [comment]
Can you be more precise? The function is-empty is not defined by induction. It is an explicit definition.

**Comment by jonaprieto** [comment]
I think it's missing the mention of what the recursor of the empty is (explicitily),
which is what you named it  `!𝟘`.  I suggested this:

```agda
𝟘-recursion  : (A : 𝓤 ̇ ) → 𝟘 → A
𝟘-recursion  A a = 𝟘-induction (λ _ → A) a
```
and 
```
!𝟘 : (A : 𝓤 ̇ ) → 𝟘 → A
!𝟘 = 𝟘-recursion
```

**Comment by martinescardo** [comment]
I see. I understand now. I will do that.

**Comment by martinescardo** [comment]
Done in d6ec03811db95cb6987731424dca475f687232e2
