### ISSUE TITLE
Various dead links in the lecture notes

### ISSUE THREAD

**Issue by wenkokke** [martinescardo/HoTT-UF-Agda-Lecture-Notes#13]
I ran [html-proofer](https://github.com/gjtorikian/html-proofer) on the lecture notes, and it detected various dead links – and, in one case, a link to a subscription-only service, which it's understandably upset about.

- ./_site/HoTT-UF-Agda.html
  *  External link https://mathscinet.ams.org/mathscinet/search/publdoc.html?arg3=&co4=AND&co5=AND&co6=AND&co7=AND&dr=all&pg4=AUCN&pg5=TI&pg6=PC&pg7=ALLF&pg8=ET&r=1&review_format=html&s4=&s5=cambridge%20lectures%20on%20intuitionism&s6=&s7=&s8=All&sort=Newest&vfpref=html&yearRangeFirst=&yearRangeSecond=&yrop=eq failed: 401 No error
  *  internally linking to Inhabitedness.html#choice, which does not exist (line 1723)
     `<a href="Inhabitedness.html#choice">axiom of choice</a>`
  *  linking to HoTT-UF-Agda.html#equivalence-induction, but equivalence-induction does not exist (line 4254)
     `<a href="HoTT-UF-Agda.html#equivalence-induction">equivalence induction</a>`
  *  linking to HoTT-UF-Agda.html#hlevels, but hlevels does not exist (line 3247)
     `<a href="HoTT-UF-Agda.html#hlevels">hlevel</a>`
  *  linking to HoTT-UF-Agda.html#hlevels, but hlevels does not exist (line 3245)
     `<a href="HoTT-UF-Agda.html#hlevels">singleton type</a>`
  *  trying to find hash of Inhabitedness.html#choice, but ./_site/HoTT-UF-Agda.html/Inhabitedness.html does not exist (line 1723)
     `<a href="Inhabitedness.html#choice">axiom of choice</a>`
- ./_site/Universes.html
  *  internally linking to MLTT-Agda, which does not exist (line 24)
     `<a href="MLTT-Agda">MLTT in Agda</a>`
  *  internally linking to toc.html#contents, which does not exist (line 16)
     `<a href="toc.html#contents"><sub>Table of contents ⇑</sub></a>`
  *  trying to find hash of toc.html#contents, but /Users/wen/Projects/HoTT-UF-Agda-Lecture-Notes/_site/Universes.html/toc.html does not exist (line 16)
     `<a href="toc.html#contents"><sub>Table of contents ⇑</sub></a>`
- ./_site/index.html
  *  internally linking to Inhabitedness.html#choice, which does not exist (line 1723)
     `<a href="Inhabitedness.html#choice">axiom of choice</a>`
  *  linking to HoTT-UF-Agda.html#equivalence-induction, but equivalence-induction does not exist (line 4254)
     `<a href="HoTT-UF-Agda.html#equivalence-induction">equivalence induction</a>`
  *  linking to HoTT-UF-Agda.html#hlevels, but hlevels does not exist (line 3247)
     `<a href="HoTT-UF-Agda.html#hlevels">hlevel</a>`
  *  linking to HoTT-UF-Agda.html#hlevels, but hlevels does not exist (line 3245)
     `<a href="HoTT-UF-Agda.html#hlevels">singleton type</a>`
  *  trying to find hash of Inhabitedness.html#choice, but ./_site/index.html/Inhabitedness.html does not exist (line 1723)
     `<a href="Inhabitedness.html#choice">axiom of choice</a>`

**Comment by martinescardo** [comment]
Thanks. I will try to fix this.

**Comment by martinescardo** [comment]
@wenkokke Hopefully I fixed the dead links now.

**Comment by wenkokke** [comment]
@martinescardo Thanks!
