### ISSUE TITLE
Spoilers for exercises in "The hlevels are upper closed"

### ISSUE THREAD

**Issue by wenkokke** [martinescardo/HoTT-UF-Agda-Lecture-Notes#15]
The exercise for *The hlevels are upper closed*...

> Exercise. Formulate and prove the following. The type 𝟙 has minimal hlevel 0. The type 𝟘 has minimal hlevel 1, the type ℕ has minimal hlevel 2. More ambitiously, **after univalence is available**, show that the type of monoids has minimal hlevel 3.

...contains spoilers for the exercise for *ℕ is a set*.

> Exercise. Prove that the types of magmas, monoids and groups have hlevel 3 (they are 1-groupoids) but not hlevel 2 (they are not sets). Prove that this is their minimal hlevel. **It is possible to do this what what we have learned so far?**

Moreover, the latter is *directly followed* by the former in the text.

**Comment by martinescardo** [comment]
Thanks. I had noticed this but I had forgotten about it. I will fix it.

**Comment by martinescardo** [comment]
Thanks. I had noticed this but I had forgotten about it. I will fix it.

**Comment by martinescardo** [comment]
I added a spoiler alert and removed duplicate exercise.
