### ISSUE TITLE
suspected typo

### ISSUE THREAD

**Issue by logicshan** [martinescardo/HoTT-UF-Agda-Lecture-Notes#16]
https://github.com/martinescardo/HoTT-UF-Agda-Lecture-Notes/blob/d4e5da69ff6c987ce2752ffb7d875debdb4133d6/HoTT-UF-Agda.lagda#L2481

Maybe I missed something at this point. I want to make clear whether this should be

`transport A p a ≡ b`

**Comment by martinescardo** [comment]
Fixed. Thanks.
