### ISSUE TITLE
typo ?

### ISSUE THREAD

**Issue by logicshan** [martinescardo/HoTT-UF-Agda-Lecture-Notes#17]
https://github.com/martinescardo/HoTT-UF-Agda-Lecture-Notes/blob/07c70787ec6babf14a01eb9bc76998f3b718ef73/HoTT-UF-Agda.lagda#L2847

the last sentence

**Comment by logicshan** [comment]
@martinescardo Sorry for not being more specific. I think there are two typos. You have fixed the first one.

`what what` -> `with what`?

**Comment by martinescardo** [comment]
I think this is now gone as it was a duplicate exercise (issue #15).
