### ISSUE TITLE
The Bourbaki Google books link is paywalled

### ISSUE THREAD

**Issue by mrakgr** [martinescardo/HoTT-UF-Agda-Lecture-Notes#19]
```
A [magma](https://en.wikipedia.org/wiki/Magma_(algebra)) is a *set* equipped with a binary operation subject to no laws
[[Bourbaki](https://books.google.co.uk/books?id=STS9aZ6F204C&pg=PA1&redir_esc=y#v=onepage&q&f=false)].  We can define the type of magmas in a universe `𝓤` as follows:
```

The Google books link is to a copyrighted book and the page does not display for me. Maybe it would be good to change it to something else?

**Comment by mrakgr** [comment]
```
A function of the underlying sets of two magmas is a called a
homomorphism when it commutes with the magma operations:

\begin{code}
is-magma-hom : (M N : Magma 𝓤) → (⟨ M ⟩ → ⟨ N ⟩) → 𝓤 ̇
is-magma-hom M N f = (x y : ⟨ M ⟩) → f (x ·⟨ M ⟩ y) ≡ f x ·⟨ N ⟩ f y
```

Isn't this distributivity rather than commutativity?

**Comment by martinescardo** [comment]
(1) Yes, the book is not free. You will need to go to a library if you want to see more than the page I want you to see. (2) "commutes" in this context is standard terminology (see e.g. https://math.stackexchange.com/questions/796783/what-is-a-homomorphism).
