### ISSUE TITLE
simple way to get agda in nixos/nix now works

### ISSUE THREAD

**Issue by timsears** [martinescardo/HoTT-UF-Agda-Lecture-Notes#9]
Thanks to pushing the latest Agda to hackage (2.6.0), the following puts you in a shell environment with agda installed. I did not issue a pull request because I am not sure how to fully test it. However it does appear to work with emacs. If you start emacs from within the environment the script that was previously installed in .emacs picks up the latest agda mode that comes with the Agda package.

```
$ nix-shell -p "haskellPackages.ghcWithPackages (p: [p.Agda])
```
Note: I am using nixpkgs/master. Not sure when nix-unstable will pick up the new version.

**Comment by timsears** [comment]
typo: should be $ nix-shell -p "haskellPackages.ghcWithPackages (p: [p.Agda])"

**Comment by tomdjong** [comment]
I cannot get this to work on Debian with `nix-shell`.
The error I get is:

```
Build with /nix/store/8vq01xmxlp9wxzilkw85rb621ag7nwmd-ghc-8.6.4.
unpacking sources
unpacking source archive /nix/store/7d86sgv4my21v3424l1c7vy6jvm3bid1-Agda-2.5.4.2.tar.gz
source root is Agda-2.5.4.2
setting SOURCE_DATE_EPOCH to timestamp 1540830739 of file Agda-2.5.4.2/stack-8.4.4.yaml
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/build/setup-package.conf.d -j4 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /build/Main.o )

Setup.hs:23:56: error:
    • Couldn't match type ‘Distribution.System.Platform -> String’
                     with ‘[Char]’
      Expected type: String
        Actual type: Distribution.System.Platform -> String
    • Probable cause: ‘exeExtension’ is applied to too few arguments
      In the second argument of ‘(<.>)’, namely ‘exeExtension’
      In the second argument of ‘(</>)’, namely ‘"agda" <.> exeExtension’
      In the second argument of ‘(</>)’, namely
        ‘"agda" </> "agda" <.> exeExtension’
   |
23 |       agda   = buildDir info </> "agda" </> "agda" <.> exeExtension
   |                                                        ^^^^^^^^^^^^
builder for '/nix/store/55gmffv0qn4ads41ah2d833g2gdw4xzg-Agda-2.5.4.2.drv' failed with exit code 1
cannot build derivation '/nix/store/d06kw6alfxqn2i3z5w8089jjv0v12igm-ghc-8.6.4-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/d06kw6alfxqn2i3z5w8089jjv0v12igm-ghc-8.6.4-with-packages.drv' failed
```

@tim Any thoughts on this?

**Comment by timsears** [comment]
The command only started working last night. You need the bleeding edge master branch of nixpkgs. Likely you are using a nix-channel which does not update so quickly. You may need to point <nixpkgs> instead of a channel to get this.

**Comment by timsears** [comment]
https://nixos.wiki/wiki/Nix_Channels

from the page...

> The unstable channels (nixpkgs/unstable and nixos/unstable) are built off of the master branch.

we need to check if Agda 2.6.0 is checked into that channel

**Comment by timsears** [comment]
nixpkgs/unstable is currently days old, so the one-liner WILL require pointing <nixpkgs> to a local git repo and checking out the master branch. That's what I do on my  nixos vm. Later I will try it on macosx and amend the one-liner.

**Comment by tomdjong** [comment]
I will keep the instructions as they are for now.
But I look forward to a tested, quicker way. Thanks.

**Comment by timsears** [comment]
The following should enable mac users. 

1. Override Agda in nixpkgs. Place 
[this file](https://gist.github.com/timsears/c4174180de6b139dd3f473b49ea09978) in ~/.config/nixpkgs/overlays/agda26.nix

2. Go have a coffee while it compiles ...

3. Enter a nix-shell...
```
$ nix-shell -p "haskellPackages.ghcWithPackages (p: [p.Agda])"
```

4. That should put you in a shell with agda and agda-mode in your path. Run
```
$ agda-mode install
```
5. Open up a .agda file in emacs and hit C-c C-l to test. Pretty colors indicate success.

Note: Step 1 should not be needed in a few days as the new version makes into your channel.  `nixpkgs-unstable` will update fastest. You will want to delete the file to allow Agda to track future version.
